=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PingApi' do
    it 'should create an instance of PingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PingApi)
    end
  end

  # unit tests for ping_get
  # Ping Harbor to check if it&#39;s alive.
  # This API simply replies a pong to indicate the process to handle API is up, disregarding the health status of dependent components.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'ping_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
