=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 1.10.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ProductsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ProductsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductsApi' do
    it 'should create an instance of ProductsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ProductsApi)
    end
  end

  # unit tests for chartrepo_charts_post
  # Upload a chart file to the defult &#39;library&#39; project.
  # Upload a chart file to the default &#39;library&#39; project. Uploading together with the prov file at the same time is also supported.
  # @param chart The chart file
  # @param [Hash] opts the optional parameters
  # @option opts [File] :prov The provance file
  # @return [nil]
  describe 'chartrepo_charts_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_health_get
  # Check the health of chart repository service.
  # Check the health of chart repository service.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'chartrepo_health_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_get
  # Get all the charts under the specified project
  # Get all the charts under the specified project
  # @param repo The project name
  # @param [Hash] opts the optional parameters
  # @return [Array<ChartInfoEntry>]
  describe 'chartrepo_repo_charts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_name_delete
  # Delete all the versions of the specified chart
  # Delete all the versions of the specified chart
  # @param repo The project name
  # @param name The chart name
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chartrepo_repo_charts_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_name_get
  # Get all the versions of the specified chart
  # Get all the versions of the specified chart
  # @param repo The project name
  # @param name The chart name
  # @param [Hash] opts the optional parameters
  # @return [ChartVersions]
  describe 'chartrepo_repo_charts_name_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_name_version_delete
  # Delete the specified chart version
  # Delete the specified chart version
  # @param repo The project name
  # @param name The chart name
  # @param version The chart version
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chartrepo_repo_charts_name_version_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_name_version_get
  # Get the specified chart version
  # Get the specified chart version
  # @param repo The project name
  # @param name The chart name
  # @param version The chart version
  # @param [Hash] opts the optional parameters
  # @return [ChartVersionDetails]
  describe 'chartrepo_repo_charts_name_version_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_name_version_labels_get
  # Return the attahced labels of chart.
  # Return the attahced labels of the specified chart version.
  # @param repo The project name
  # @param name The chart name
  # @param version The chart version
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chartrepo_repo_charts_name_version_labels_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_name_version_labels_id_delete
  # Remove label from chart.
  # Remove label from the specified chart version.
  # @param repo The project name
  # @param name The chart name
  # @param version The chart version
  # @param id The label ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chartrepo_repo_charts_name_version_labels_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_name_version_labels_post
  # Mark label to chart.
  # Mark label to the specified chart version.
  # @param repo The project name
  # @param name The chart name
  # @param version The chart version
  # @param label The label being marked to the chart version
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chartrepo_repo_charts_name_version_labels_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_charts_post
  # Upload a chart file to the specified project.
  # Upload a chart file to the specified project. With this API, the corresponding provance file can be uploaded together with chart file at once.
  # @param repo The project name
  # @param chart The chart file
  # @param [Hash] opts the optional parameters
  # @option opts [File] :prov The provance file
  # @return [nil]
  describe 'chartrepo_repo_charts_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for chartrepo_repo_prov_post
  # Upload a provance file to the specified project.
  # Upload a provance file to the specified project. The provance file should be targeted for an existing chart file.
  # @param repo The project name
  # @param prov The provance file
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'chartrepo_repo_prov_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for configurations_get
  # Get system configurations.
  # This endpoint is for retrieving system configurations that only provides for admin user. 
  # @param [Hash] opts the optional parameters
  # @return [ConfigurationsResponse]
  describe 'configurations_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for configurations_put
  # Modify system configurations.
  # This endpoint is for modifying system configurations that only provides for admin user. 
  # @param configurations The configuration map can contain a subset of the attributes of the schema, which are to be updated.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'configurations_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for email_ping_post
  # Test connection and authentication with email server.
  # Test connection and authentication with email server. 
  # @param [Hash] opts the optional parameters
  # @option opts [EmailServerSetting] :settings Email server settings, if some of the settings are not assigned, they will be read from system configuration.
  # @return [nil]
  describe 'email_ping_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for health_get
  # Health check API
  # The endpoint returns the health stauts of the system. 
  # @param [Hash] opts the optional parameters
  # @return [OverallHealthStatus]
  describe 'health_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for internal_switchquota_put
  # Enable or disable quota.
  # This endpoint is for enable/disable quota. When quota is disabled, no resource require/release in image/chart push and delete. 
  # @param switcher 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'internal_switchquota_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for internal_syncquota_post
  # Sync quota from registry/chart to DB.
  # This endpoint is for syncing quota usage of registry/chart with database. 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'internal_syncquota_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for internal_syncregistry_post
  # Sync repositories from registry to DB.
  # This endpoint is for syncing all repositories of registry with database. 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'internal_syncregistry_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_get
  # List labels according to the query strings.
  # This endpoint let user list labels by name, scope and project_id 
  # @param scope The label scope. Valid values are g and p. g for global labels and p for project labels.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name The label name.
  # @option opts [Integer] :project_id Relevant project ID, required when scope is p.
  # @option opts [Integer] :page The page nubmer.
  # @option opts [Integer] :page_size The size of per page.
  # @return [Array<Label>]
  describe 'labels_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_id_delete
  # Delete the label specified by ID.
  # Delete the label specified by ID. 
  # @param id Label ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'labels_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_id_get
  # Get the label specified by ID.
  # This endpoint let user get the label by specific ID. 
  # @param id Label ID
  # @param [Hash] opts the optional parameters
  # @return [Label]
  describe 'labels_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_id_put
  # Update the label properties.
  # This endpoint let user update label properties. 
  # @param id Label ID
  # @param label The updated label json object.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'labels_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_id_resources_get
  # Get the resources that the label is referenced by.
  # This endpoint let user get the resources that the label is referenced by. Only the replication policies are returned for now. 
  # @param id Label ID
  # @param [Hash] opts the optional parameters
  # @return [Resource]
  describe 'labels_id_resources_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for labels_post
  # Post creates a label
  # This endpoint let user creates a label. 
  # @param label The json object of label.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'labels_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ldap_groups_search_get
  # Search available ldap groups.
  # This endpoint searches the available ldap groups based on related configuration parameters. support to search by groupname or groupdn. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :groupname Ldap group name
  # @option opts [String] :groupdn The LDAP group DN
  # @return [Array<UserGroup>]
  describe 'ldap_groups_search_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ldap_ping_post
  # Ping available ldap service.
  # This endpoint ping the available ldap service for test related configuration parameters. 
  # @param [Hash] opts the optional parameters
  # @option opts [LdapConf] :ldapconf ldap configuration. support input ldap service configuration. If it&#39;s a empty request, will load current configuration from the system.
  # @return [nil]
  describe 'ldap_ping_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ldap_users_import_post
  # Import selected available ldap users.
  # This endpoint adds the selected available ldap users to harbor based on related configuration parameters from the system. System will try to guess the user email address and realname, add to harbor user information. If have errors when import user, will return the list of importing failed uid and the failed reason. 
  # @param uid_list The uid listed for importing. This list will check users validity of ldap service based on configuration from the system.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ldap_users_import_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ldap_users_search_get
  # Search available ldap users.
  # This endpoint searches the available ldap users based on related configuration parameters. Support searched by input ladp configuration, load configuration from the system and specific filter. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username Registered user ID
  # @return [Array<LdapUsers>]
  describe 'ldap_users_search_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for logs_get
  # Get recent logs of the projects which the user is a member of
  # This endpoint let user see the recent operation logs of the projects which he is member of 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username Username of the operator.
  # @option opts [String] :repository The name of repository
  # @option opts [String] :tag The name of tag
  # @option opts [String] :operation The operation
  # @option opts [String] :begin_timestamp The begin timestamp
  # @option opts [String] :end_timestamp The end timestamp
  # @option opts [Integer] :page The page number, default is 1.
  # @option opts [Integer] :page_size The size of per page, default is 10, maximum is 100.
  # @return [Array<AccessLog>]
  describe 'logs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_get
  # List projects
  # This endpoint returns all projects created by Harbor, and can be filtered by project name. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name The name of project.
  # @option opts [BOOLEAN] :public The project is public or private.
  # @option opts [String] :owner The name of project owner.
  # @option opts [Integer] :page The page number, default is 1.
  # @option opts [Integer] :page_size The size of per page, default is 10, maximum is 100.
  # @return [Array<Project>]
  describe 'projects_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_head
  # Check if the project name user provided already exists.
  # This endpoint is used to check if the project name user provided already exist. 
  # @param project_name Project name for checking exists.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_head test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_post
  # Create a new project.
  # This endpoint is for user to create a new project. 
  # @param project New created project.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_delete
  # Delete project by projectID
  # This endpoint is aimed to delete project by project ID. 
  # @param project_id Project ID of project which will be deleted.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_get
  # Return specific project detail information
  # This endpoint returns specific project information by project ID. 
  # @param project_id Project ID for filtering results.
  # @param [Hash] opts the optional parameters
  # @return [Project]
  describe 'projects_project_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_immutabletagrules_get
  # List all immutable tag rules of current project
  # This endpoint returns the immutable tag rules of a project 
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<ImmutableTagRule>]
  describe 'projects_project_id_immutabletagrules_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_immutabletagrules_id_delete
  # Delete the immutable tag rule.
  # @param project_id Relevant project ID.
  # @param id Immutable tag rule ID.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_immutabletagrules_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_immutabletagrules_id_put
  # Update the immutable tag rule or enable or disable the rule
  # @param project_id Relevant project ID.
  # @param id Immutable tag rule ID.
  # @param [Hash] opts the optional parameters
  # @option opts [ImmutableTagRule] :immutabletagrule 
  # @return [nil]
  describe 'projects_project_id_immutabletagrules_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_immutabletagrules_post
  # Add an immutable tag rule to current project
  # This endpoint add an immutable tag rule to the project 
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @option opts [ImmutableTagRule] :immutabletagrule 
  # @return [nil]
  describe 'projects_project_id_immutabletagrules_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_logs_get
  # Get access logs accompany with a relevant project.
  # This endpoint let user search access logs filtered by operations and date time ranges. 
  # @param project_id Relevant project ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username Username of the operator.
  # @option opts [String] :repository The name of repository
  # @option opts [String] :tag The name of tag
  # @option opts [String] :operation The operation
  # @option opts [String] :begin_timestamp The begin timestamp
  # @option opts [String] :end_timestamp The end timestamp
  # @option opts [Integer] :page The page number, default is 1.
  # @option opts [Integer] :page_size The size of per page, default is 10, maximum is 100.
  # @return [Array<AccessLog>]
  describe 'projects_project_id_logs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_members_get
  # Get all project member information
  # Get all project member information
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :entityname The entity name to search.
  # @return [Array<ProjectMemberEntity>]
  describe 'projects_project_id_members_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_members_mid_delete
  # Delete project member
  # @param project_id Relevant project ID.
  # @param mid Member ID.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_members_mid_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_members_mid_get
  # Get the project member information
  # Get the project member information
  # @param project_id Relevant project ID.
  # @param mid The member ID
  # @param [Hash] opts the optional parameters
  # @return [ProjectMemberEntity]
  describe 'projects_project_id_members_mid_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_members_mid_put
  # Update project member
  # Update project member relationship
  # @param project_id Relevant project ID.
  # @param mid Member ID.
  # @param [Hash] opts the optional parameters
  # @option opts [RoleRequest] :role 
  # @return [nil]
  describe 'projects_project_id_members_mid_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_members_post
  # Create project member
  # Create project member relationship, the member can be one of the user_member and group_member,  The user_member need to specify user_id or username. If the user already exist in harbor DB, specify the user_id,  If does not exist in harbor DB, it will SearchAndOnBoard the user. The group_member need to specify id or ldap_group_dn. If the group already exist in harbor DB. specify the user group&#39;s id,  If does not exist, it will SearchAndOnBoard the group. 
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @option opts [ProjectMember] :project_member 
  # @return [nil]
  describe 'projects_project_id_members_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_metadatas_get
  # Get project metadata.
  # This endpoint returns metadata of the project specified by project ID. 
  # @param project_id The ID of project.
  # @param [Hash] opts the optional parameters
  # @return [ProjectMetadata]
  describe 'projects_project_id_metadatas_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_metadatas_meta_name_delete
  # Delete metadata of a project
  # This endpoint is aimed to delete metadata of a project. 
  # @param project_id The ID of project.
  # @param meta_name The name of metadat.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_metadatas_meta_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_metadatas_meta_name_get
  # Get project metadata
  # This endpoint returns specified metadata of a project. 
  # @param project_id Project ID for filtering results.
  # @param meta_name The name of metadat.
  # @param [Hash] opts the optional parameters
  # @return [ProjectMetadata]
  describe 'projects_project_id_metadatas_meta_name_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_metadatas_meta_name_put
  # Update metadata of a project.
  # This endpoint is aimed to update the metadata of a project. 
  # @param project_id The ID of project.
  # @param meta_name The name of metadat.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_metadatas_meta_name_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_metadatas_post
  # Add metadata for the project.
  # This endpoint is aimed to add metadata of a project. 
  # @param project_id Selected project ID.
  # @param metadata The metadata of project.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_metadatas_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_put
  # Update properties for a selected project.
  # This endpoint is aimed to update the properties of a project. 
  # @param project_id Selected project ID.
  # @param project Updates of project.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_robots_get
  # Get all robot accounts of specified project
  # Get all robot accounts of specified project
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<RobotAccount>]
  describe 'projects_project_id_robots_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_robots_post
  # Create a robot account for project
  # Create a robot account for project
  # @param project_id Relevant project ID.
  # @param robot Request body of creating a robot account.
  # @param [Hash] opts the optional parameters
  # @return [RobotAccountPostRep]
  describe 'projects_project_id_robots_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_robots_robot_id_delete
  # Delete the specified robot account
  # Delete the specified robot account
  # @param project_id Relevant project ID.
  # @param robot_id The ID of robot account.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_robots_robot_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_robots_robot_id_get
  # Return the infor of the specified robot account.
  # Return the infor of the specified robot account.
  # @param project_id Relevant project ID.
  # @param robot_id The ID of robot account.
  # @param [Hash] opts the optional parameters
  # @return [RobotAccount]
  describe 'projects_project_id_robots_robot_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_robots_robot_id_put
  # Update status of robot account.
  # Used to disable/enable a specified robot account.
  # @param project_id Relevant project ID.
  # @param robot_id The ID of robot account.
  # @param robot Request body of enable/disable a robot account.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_robots_robot_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_scanner_candidates_get
  # Get scanner registration candidates for configurating project level scanner
  # Retrieve the system configured scanner registrations as candidates of setting project level scanner. 
  # @param project_id The project identifier.
  # @param [Hash] opts the optional parameters
  # @return [Array<ScannerRegistration>]
  describe 'projects_project_id_scanner_candidates_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_scanner_get
  # Get project level scanner
  # Get the scanner registration of the specified project. If no scanner registration is configured for the specified project, the system default scanner registration will be returned.
  # @param project_id The project identifier.
  # @param [Hash] opts the optional parameters
  # @return [ScannerRegistration]
  describe 'projects_project_id_scanner_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_summary_get
  # Get summary of the project.
  # Get summary of the project.
  # @param project_id Relevant project ID
  # @param [Hash] opts the optional parameters
  # @return [ProjectSummary]
  describe 'projects_project_id_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_jobs_get
  # List project webhook jobs
  # This endpoint returns webhook jobs of a project. 
  # @param project_id Relevant project ID.
  # @param policy_id The policy ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<WebhookJob>]
  describe 'projects_project_id_webhook_jobs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_lasttrigger_get
  # Get project webhook policy last trigger info
  # This endpoint returns last trigger information of project webhook policy. 
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<WebhookLastTrigger>]
  describe 'projects_project_id_webhook_lasttrigger_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_policies_get
  # List project webhook policies.
  # This endpoint returns webhook policies of a project. 
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<WebhookPolicy>]
  describe 'projects_project_id_webhook_policies_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_policies_policy_id_delete
  # Delete webhook policy of a project
  # This endpoint is aimed to delete webhookpolicy of a project. 
  # @param project_id Relevant project ID.
  # @param policy_id The id of webhook policy.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_webhook_policies_policy_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_policies_policy_id_get
  # Get project webhook policy
  # This endpoint returns specified webhook policy of a project. 
  # @param project_id Relevant project ID.
  # @param policy_id The id of webhook policy.
  # @param [Hash] opts the optional parameters
  # @return [WebhookPolicy]
  describe 'projects_project_id_webhook_policies_policy_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_policies_policy_id_put
  # Update webhook policy of a project.
  # This endpoint is aimed to update the webhook policy of a project. 
  # @param project_id Relevant project ID.
  # @param policy_id The id of webhook policy.
  # @param policy All properties needed except \&quot;id\&quot;, \&quot;project_id\&quot;, \&quot;creation_time\&quot;, \&quot;update_time\&quot;.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_webhook_policies_policy_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_policies_post
  # Create project webhook policy.
  # This endpoint create a webhook policy if the project does not have one. 
  # @param project_id Relevant project ID
  # @param policy Properties \&quot;targets\&quot; and \&quot;event_types\&quot; needed.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_webhook_policies_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_webhook_policies_test_post
  # Test project webhook connection
  # This endpoint tests webhook connection of a project. 
  # @param project_id Relevant project ID.
  # @param policy Only property \&quot;targets\&quot; needed.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'projects_project_id_webhook_policies_test_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for quotas_get
  # List quotas
  # List quotas
  # @param [Hash] opts the optional parameters
  # @option opts [String] :reference The reference type of quota.
  # @option opts [String] :reference_id The reference id of quota.
  # @option opts [String] :sort Sort method, valid values include: &#39;hard.resource_name&#39;, &#39;-hard.resource_name&#39;, &#39;used.resource_name&#39;, &#39;-used.resource_name&#39;. Here &#39;-&#39; stands for descending order, resource_name should be the real resource name of the quota. 
  # @option opts [Integer] :page The page number, default is 1.
  # @option opts [Integer] :page_size The size of per page, default is 10, maximum is 100.
  # @return [Array<Quota>]
  describe 'quotas_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for quotas_id_get
  # Get the specified quota
  # Get the specified quota
  # @param id Quota ID
  # @param [Hash] opts the optional parameters
  # @return [Quota]
  describe 'quotas_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for quotas_id_put
  # Update the specified quota
  # Update hard limits of the specified quota
  # @param id Quota ID
  # @param hard The new hard limits for the quota
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'quotas_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_get
  # List registries.
  # This endpoint let user list filtered registries by name, if name is nil, list returns all registries. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name Registry&#39;s name.
  # @return [Array<Registry>]
  describe 'registries_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_id_delete
  # Delete specific registry.
  # This endpoint is for to delete specific registry. 
  # @param id The registry&#39;s ID.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'registries_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_id_get
  # Get registry.
  # This endpoint is for get specific registry.
  # @param id The registry ID.
  # @param [Hash] opts the optional parameters
  # @return [Registry]
  describe 'registries_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_id_info_get
  # Get registry info.
  # Get the info of one specific registry.
  # @param id The registry ID.
  # @param [Hash] opts the optional parameters
  # @return [RegistryInfo]
  describe 'registries_id_info_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_id_namespace_get
  # List namespaces of registry
  # This endpoint let user list namespaces of registry according to query. 
  # @param id The registry ID.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name The name of namespace.
  # @return [Array<Namespace>]
  describe 'registries_id_namespace_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_id_put
  # Update a given registry.
  # This endpoint is for update a given registry. 
  # @param id The registry&#39;s ID.
  # @param repo_target Updates registry.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'registries_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_ping_post
  # Ping status of a registry.
  # This endpoint checks status of a registry, the registry can be given by ID or URL (together with credential) 
  # @param registry Registry to ping.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'registries_ping_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for registries_post
  # Create a new registry.
  # This endpoint is for user to create a new registry. 
  # @param registry New created registry.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'registries_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_adapters_get
  # List supported adapters.
  # This endpoint let user list supported adapters. 
  # @param [Hash] opts the optional parameters
  # @return [Array<String>]
  describe 'replication_adapters_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_executions_get
  # List replication executions.
  # This endpoint let user list replication executions. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :policy_id The policy ID.
  # @option opts [String] :status The execution status.
  # @option opts [String] :trigger The trigger mode.
  # @option opts [Integer] :page The page.
  # @option opts [Integer] :page_size The page size.
  # @return [Array<ReplicationExecution>]
  describe 'replication_executions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_executions_id_get
  # Get the execution of the replication.
  # This endpoint is for user to get one execution of the replication. 
  # @param id The execution ID.
  # @param [Hash] opts the optional parameters
  # @return [ReplicationExecution]
  describe 'replication_executions_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_executions_id_put
  # Stop the execution of the replication.
  # This endpoint is for user to stop one execution of the replication. 
  # @param id The execution ID.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replication_executions_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_executions_id_tasks_get
  # Get the task list of one execution.
  # This endpoint is for user to get the task list of one execution. 
  # @param id The execution ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<ReplicationTask>]
  describe 'replication_executions_id_tasks_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_executions_id_tasks_task_id_log_get
  # Get the log of one task.
  # This endpoint is for user to get the log of one task. 
  # @param id The execution ID.
  # @param task_id The task ID.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replication_executions_id_tasks_task_id_log_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_executions_post
  # Start one execution of the replication.
  # This endpoint is for user to start one execution of the replication. 
  # @param execution The execution that needs to be started, only the property \&quot;policy_id\&quot; is needed.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replication_executions_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_policies_get
  # List replication policies
  # This endpoint let user list replication policies 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name The replication policy name.
  # @option opts [Integer] :page The page nubmer.
  # @option opts [Integer] :page_size The size of per page.
  # @return [Array<ReplicationPolicy>]
  describe 'replication_policies_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_policies_id_delete
  # Delete the replication policy specified by ID.
  # Delete the replication policy specified by ID. 
  # @param id Replication policy ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replication_policies_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_policies_id_get
  # Get replication policy.
  # This endpoint let user get replication policy by specific ID. 
  # @param id policy ID
  # @param [Hash] opts the optional parameters
  # @return [ReplicationPolicy]
  describe 'replication_policies_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_policies_id_put
  # Update the replication policy
  # This endpoint let user update policy. 
  # @param id policy ID
  # @param policy The replication policy model.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replication_policies_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replication_policies_post
  # Create a replication policy
  # This endpoint let user create a replication policy 
  # @param policy The policy model.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replication_policies_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_get
  # Get repositories accompany with relevant project and repo name.
  # This endpoint lets user search repositories accompanying with relevant project ID and repo name. Repositories can be sorted by repo name, creation_time, update_time in either ascending or descending order. 
  # @param project_id Relevant project ID.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :q Repo name for filtering results.
  # @option opts [String] :sort Sort method, valid values include: &#39;name&#39;, &#39;-name&#39;, &#39;creation_time&#39;, &#39;-creation_time&#39;, &#39;update_time&#39;, &#39;-update_time&#39;. Here &#39;-&#39; stands for descending order. 
  # @option opts [Integer] :label_id The ID of label used to filter the result.
  # @option opts [Integer] :page The page number, default is 1.
  # @option opts [Integer] :page_size The size of per page, default is 10, maximum is 100.
  # @return [Array<Repository>]
  describe 'repositories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_delete
  # Delete a repository.
  # This endpoint let user delete a repository with name. 
  # @param repo_name The name of repository which will be deleted.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_labels_get
  # Get labels of a repository.
  # Get labels of a repository specified by the repo_name. 
  # @param repo_name The name of repository.
  # @param [Hash] opts the optional parameters
  # @return [Array<Label>]
  describe 'repositories_repo_name_labels_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_labels_label_id_delete
  # Delete label from the repository.
  # Delete the label from the repository specified by the repo_name. 
  # @param repo_name The name of repository.
  # @param label_id The ID of label.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_labels_label_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_labels_post
  # Add a label to the repository.
  # Add a label to the repository. 
  # @param repo_name The name of repository.
  # @param label Only the ID property is required.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_labels_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_put
  # Update description of the repository.
  # This endpoint is used to update description of the repository. 
  # @param repo_name The name of repository which will be deleted.
  # @param description The description of the repository.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_signatures_get
  # Get signature information of a repository
  # This endpoint aims to retrieve signature information of a repository, the data is from the nested notary instance of Harbor. If the repository does not have any signature information in notary, this API will return an empty list with response code 200, instead of 404 
  # @param repo_name repository name.
  # @param [Hash] opts the optional parameters
  # @return [Array<RepoSignature>]
  describe 'repositories_repo_name_signatures_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_get
  # Get tags of a relevant repository.
  # This endpoint aims to retrieve tags from a relevant repository. If deployed with Notary, the signature property of response represents whether the image is singed or not. If the property is null, the image is unsigned. 
  # @param repo_name Relevant repository name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :label_id A label ID.
  # @option opts [BOOLEAN] :detail Bool value indicating whether return detailed information of the tag, such as vulnerability scan info, if set to false, only tag name is returned.
  # @return [Array<DetailedTag>]
  describe 'repositories_repo_name_tags_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_post
  # Retag an image
  # This endpoint tags an existing image with another tag in this repo, source images can be in different repos or projects. 
  # @param repo_name Relevant repository name.
  # @param request Request to give source image and target tag.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_tags_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_delete
  # Delete a tag in a repository.
  # This endpoint let user delete tags with repo name and tag. 
  # @param repo_name The name of repository which will be deleted.
  # @param tag Tag of a repository.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_tags_tag_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_get
  # Get the tag of the repository.
  # This endpoint aims to retrieve the tag of the repository. If deployed with Notary, the signature property of response represents whether the image is singed or not. If the property is null, the image is unsigned. 
  # @param repo_name Relevant repository name.
  # @param tag Tag of the repository.
  # @param [Hash] opts the optional parameters
  # @return [DetailedTag]
  describe 'repositories_repo_name_tags_tag_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_labels_get
  # Get labels of an image.
  # Get labels of an image specified by the repo_name and tag. 
  # @param repo_name The name of repository.
  # @param tag The tag of the image.
  # @param [Hash] opts the optional parameters
  # @return [Array<Label>]
  describe 'repositories_repo_name_tags_tag_labels_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_labels_label_id_delete
  # Delete label from the image.
  # Delete the label from the image specified by the repo_name and tag. 
  # @param repo_name The name of repository.
  # @param tag The tag of the image.
  # @param label_id The ID of label.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_tags_tag_labels_label_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_labels_post
  # Add a label to image.
  # Add a label to the image. 
  # @param repo_name The name of repository.
  # @param tag The tag of the image.
  # @param label Only the ID property is required.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_tags_tag_labels_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_manifest_get
  # Get manifests of a relevant repository.
  # This endpoint aims to retreive manifests from a relevant repository. 
  # @param repo_name Repository name
  # @param tag Tag name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :version The version of manifest, valid value are \&quot;v1\&quot; and \&quot;v2\&quot;, default is \&quot;v2\&quot;
  # @return [Manifest]
  describe 'repositories_repo_name_tags_tag_manifest_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_scan_post
  # Scan the image.
  # Trigger a scan targeting the artifact identified by the repo_name and tag. 
  # @param repo_name Repository name
  # @param tag Tag name
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'repositories_repo_name_tags_tag_scan_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_repo_name_tags_tag_scan_uuid_log_get
  # Get scan log
  # Get the log text stream for the given artifact and scan action.
  # @param repo_name Repository name
  # @param tag Tag name
  # @param uuid the scan unique identifier
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'repositories_repo_name_tags_tag_scan_uuid_log_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repositories_top_get
  # Get public repositories which are accessed most.
  # This endpoint aims to let users see the most popular public repositories 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count The number of the requested public repositories, default is 10 if not provided.
  # @return [Array<Repository>]
  describe 'repositories_top_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_id_executions_eid_patch
  # Stop a Retention job
  # Stop a Retention job, only support \&quot;stop\&quot; action now.
  # @param id Retention ID.
  # @param eid Retention execution ID.
  # @param action The action, only support \&quot;stop\&quot; now.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'retentions_id_executions_eid_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_id_executions_eid_tasks_get
  # Get Retention job tasks
  # Get Retention job tasks, each repository as a task.
  # @param id Retention ID.
  # @param eid Retention execution ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<RetentionExecutionTask>]
  describe 'retentions_id_executions_eid_tasks_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_id_executions_eid_tasks_tid_get
  # Get Retention job task log
  # Get Retention job task log, tags ratain or deletion detail will be shown in a table.
  # @param id Retention ID.
  # @param eid Retention execution ID.
  # @param tid Retention execution ID.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'retentions_id_executions_eid_tasks_tid_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_id_executions_get
  # Get a Retention job
  # Get a Retention job, job status may be delayed before job service schedule it up.
  # @param id Retention ID.
  # @param [Hash] opts the optional parameters
  # @return [Array<RetentionExecution>]
  describe 'retentions_id_executions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_id_executions_post
  # Trigger a Retention job
  # Trigger a Retention job, if dry_run is True, nothing would be deleted actually.
  # @param id Retention ID.
  # @param action 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'retentions_id_executions_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_id_get
  # Get Retention Policy
  # Get Retention Policy.
  # @param id Retention ID.
  # @param [Hash] opts the optional parameters
  # @return [RetentionPolicy]
  describe 'retentions_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_id_put
  # Update Retention Policy
  # Update Retention Policy, you can reference metadatas API for the policy model. You can check project metadatas to find whether a retention policy is already binded. This method should only be called when retention policy has already binded to project. 
  # @param id Retention ID.
  # @param policy 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'retentions_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_metadatas_get
  # Get Retention Metadatas
  # Get Retention Metadatas.
  # @param [Hash] opts the optional parameters
  # @return [RetentionMetadata]
  describe 'retentions_metadatas_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retentions_post
  # Create Retention Policy
  # Create Retention Policy, you can reference metadatas API for the policy model. You can check project metadatas to find whether a retention policy is already binded. This method should only be called when no retention policy binded to project yet. 
  # @param policy Create Retention Policy successfully.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'retentions_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scanners_get
  # List scanner registrations
  # Returns a list of currently configured scanner registrations. 
  # @param [Hash] opts the optional parameters
  # @return [Array<ScannerRegistration>]
  describe 'scanners_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scanners_ping_post
  # Tests scanner registration settings
  # Pings scanner adapter to test endpoint URL and authorization settings. 
  # @param settings A scanner registration settings to be tested.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'scanners_ping_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scanners_registration_id_get
  # Get a scanner registration details
  # Retruns the details of the specified scanner registration. 
  # @param registration_id The scanner registration identifer.
  # @param [Hash] opts the optional parameters
  # @return [ScannerRegistration]
  describe 'scanners_registration_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scanners_registration_id_metadata_get
  # Get the metadata of the specified scanner registration
  # Get the metadata of the specified scanner registration, including the capabilities and customzied properties. 
  # @param registration_id The scanner registration identifier.
  # @param [Hash] opts the optional parameters
  # @return [ScannerAdapterMetadata]
  describe 'scanners_registration_id_metadata_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scans_all_metrics_get
  # Get the metrics of the latest scan all process
  # Get the metrics of the latest scan all process
  # @param [Hash] opts the optional parameters
  # @return [Stats]
  describe 'scans_all_metrics_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scans_schedule_metrics_get
  # Get the metrics of the latest scheduled scan all process
  # Get the metrics of the latest scheduled scan all process
  # @param [Hash] opts the optional parameters
  # @return [Stats]
  describe 'scans_schedule_metrics_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_get
  # Search for projects, repositories and helm charts
  # The Search endpoint returns information about the projects ,repositories  and helm charts offered at public status or related to the current logged in user. The response includes the project, repository list and charts in a proper display order. 
  # @param q Search parameter for project and repository name.
  # @param [Hash] opts the optional parameters
  # @return [Array<Search>]
  describe 'search_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for statistics_get
  # Get projects number and repositories number relevant to the user
  # This endpoint is aimed to statistic all of the projects number and repositories number relevant to the logined user, also the public projects number and repositories number. If the user is admin, he can also get total projects number and total repositories number. 
  # @param [Hash] opts the optional parameters
  # @return [StatisticMap]
  describe 'statistics_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_cve_whitelist_get
  # Get the system level whitelist of CVE.
  # Get the system level whitelist of CVE.  This API can be called by all authenticated users.
  # @param [Hash] opts the optional parameters
  # @return [CVEWhitelist]
  describe 'system_cve_whitelist_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_cve_whitelist_put
  # Update the system level whitelist of CVE.
  # This API overwrites the system level whitelist of CVE with the list in request body.  Only system Admin has permission to call this API.
  # @param [Hash] opts the optional parameters
  # @option opts [CVEWhitelist] :whitelist The whitelist with new content
  # @return [nil]
  describe 'system_cve_whitelist_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_gc_get
  # Get gc results.
  # This endpoint let user get latest ten gc results.
  # @param [Hash] opts the optional parameters
  # @return [Array<GCResult>]
  describe 'system_gc_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_gc_id_get
  # Get gc status.
  # This endpoint let user get gc status filtered by specific ID.
  # @param id Relevant job ID
  # @param [Hash] opts the optional parameters
  # @return [GCResult]
  describe 'system_gc_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_gc_id_log_get
  # Get gc job log.
  # This endpoint let user get gc job logs filtered by specific ID.
  # @param id Relevant job ID
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'system_gc_id_log_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_gc_schedule_get
  # Get gc&#39;s schedule.
  # This endpoint is for get schedule of gc job.
  # @param [Hash] opts the optional parameters
  # @return [AdminJobSchedule]
  describe 'system_gc_schedule_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_gc_schedule_post
  # Create a gc schedule.
  # This endpoint is for update gc schedule. 
  # @param schedule Updates of gc&#39;s schedule.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'system_gc_schedule_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_gc_schedule_put
  # Update gc&#39;s schedule.
  # This endpoint is for update gc schedule. 
  # @param schedule Updates of gc&#39;s schedule.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'system_gc_schedule_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_oidc_ping_post
  # Test the OIDC endpoint.
  # Test the OIDC endpoint, the setting of the endpoint is provided in the request.  This API can only be called by system admin.
  # @param endpoint Request body for OIDC endpoint to be tested.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'system_oidc_ping_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_scan_all_schedule_get
  # Get scan_all&#39;s schedule.
  # This endpoint is for getting a schedule for the scan all job, which scans all of images in Harbor.
  # @param [Hash] opts the optional parameters
  # @return [AdminJobSchedule]
  describe 'system_scan_all_schedule_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_scan_all_schedule_post
  # Create a schedule or a manual trigger for the scan all job.
  # This endpoint is for creating a schedule or a manual trigger for the scan all job, which scans all of images in Harbor. 
  # @param schedule Create a schedule or a manual trigger for the scan all job.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'system_scan_all_schedule_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_scan_all_schedule_put
  # Update scan all&#39;s schedule.
  # This endpoint is for updating the schedule of scan all job, which scans all of images in Harbor. 
  # @param schedule Updates the schedule of scan all job, which scans all of images in Harbor.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'system_scan_all_schedule_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for systeminfo_get
  # Get general system info
  # This API is for retrieving general system info, this can be called by anonymous request. 
  # @param [Hash] opts the optional parameters
  # @return [GeneralInfo]
  describe 'systeminfo_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for systeminfo_getcert_get
  # Get default root certificate.
  # This endpoint is for downloading a default root certificate. 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'systeminfo_getcert_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for systeminfo_volumes_get
  # Get system volume info (total/free size).
  # This endpoint is for retrieving system volume info that only provides for admin user. 
  # @param [Hash] opts the optional parameters
  # @return [SystemInfo]
  describe 'systeminfo_volumes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for usergroups_get
  # Get all user groups information
  # Get all user groups information
  # @param [Hash] opts the optional parameters
  # @return [Array<UserGroup>]
  describe 'usergroups_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for usergroups_group_id_delete
  # Delete user group
  # Delete user group
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'usergroups_group_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for usergroups_group_id_get
  # Get user group information
  # Get user group information
  # @param group_id Group ID
  # @param [Hash] opts the optional parameters
  # @return [UserGroup]
  describe 'usergroups_group_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for usergroups_group_id_put
  # Update group information
  # Update user group information
  # @param group_id Group ID
  # @param [Hash] opts the optional parameters
  # @option opts [UserGroup] :usergroup 
  # @return [nil]
  describe 'usergroups_group_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for usergroups_post
  # Create user group
  # Create user group information
  # @param [Hash] opts the optional parameters
  # @option opts [UserGroup] :usergroup 
  # @return [nil]
  describe 'usergroups_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_current_get
  # Get current user info.
  # This endpoint is to get the current user information. 
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'users_current_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_current_permissions_get
  # Get current user permissions.
  # This endpoint is to get the current user permissions. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :scope Get permissions of the scope
  # @option opts [BOOLEAN] :relative If true, the resources in the response are relative to the scope, eg for resource &#39;/project/1/repository&#39; if relative is &#39;true&#39; then the resource in response will be &#39;repository&#39;. 
  # @return [Array<Permission>]
  describe 'users_current_permissions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_get
  # Get registered users of Harbor.
  # This endpoint is for user to search registered users, support for filtering results with username.Notice, by now this operation is only for administrator. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username Username for filtering results.
  # @option opts [String] :email Email for filtering results.
  # @option opts [Integer] :page The page number, default is 1.
  # @option opts [Integer] :page_size The size of per page.
  # @return [Array<User>]
  describe 'users_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_post
  # Creates a new user account.
  # This endpoint is to create a user if the user does not already exist. 
  # @param user New created user.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_search_get
  # Search users by username
  # This endpoint is to search the users by username. 
  # @param username Username for filtering results.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page number, default is 1.
  # @option opts [Integer] :page_size The size of per page.
  # @return [Array<UserSearch>]
  describe 'users_search_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_user_id_cli_secret_put
  # Set CLI secret for a user.
  # This endpoint let user generate a new CLI secret for himself.  This API only works when auth mode is set to &#39;OIDC&#39;. Once this API returns with successful status, the old secret will be invalid, as there will be only one CLI secret for a user. 
  # @param user_id User ID
  # @param input_secret JSON object that includes the new secret
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_user_id_cli_secret_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_user_id_delete
  # Mark a registered user as be removed.
  # This endpoint let administrator of Harbor mark a registered user as be removed.It actually won&#39;t be deleted from DB. 
  # @param user_id User ID for marking as to be removed.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_user_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_user_id_get
  # Get a user&#39;s profile.
  # Get user&#39;s profile with user id. 
  # @param user_id Registered user ID
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'users_user_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_user_id_password_put
  # Change the password on a user that already exists.
  # This endpoint is for user to update password. Users with the admin role can change any user&#39;s password. Guest users can change only their own password. 
  # @param user_id Registered user ID.
  # @param password Password to be updated, the attribute &#39;old_password&#39; is optional when the API is called by the system administrator.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_user_id_password_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_user_id_put
  # Update a registered user to change his profile.
  # This endpoint let a registered user change his profile. 
  # @param user_id Registered user ID
  # @param profile Only email, realname and comment can be modified.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_user_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_user_id_sysadmin_put
  # Update a registered user to change to be an administrator of Harbor.
  # This endpoint let a registered user change to be an administrator of Harbor. 
  # @param user_id Registered user ID
  # @param has_admin_role Toggle a user to admin or not.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_user_id_sysadmin_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
