=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InputSecret
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InputSecret' do
  before do
    # run before each test
    @instance = SwaggerClient::InputSecret.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InputSecret' do
    it 'should create an instance of InputSecret' do
      expect(@instance).to be_instance_of(SwaggerClient::InputSecret)
    end
  end
  describe 'test attribute "secret"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
